//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_Marcin
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresy
    {
        public int ID_adresu { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Kod_pocztowy { get; set; }
        public Nullable<int> ID_klienta { get; set; }
    
        public virtual klienci klienci { get; set; }
    }
}
