//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_Marcin
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pracownicy()
        {
            this.wypozyczenia = new HashSet<wypozyczenia>();
        }
    
        public int ID_pracownika { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public System.DateTime Data_przyjecia { get; set; }
        public string Pesel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wypozyczenia> wypozyczenia { get; set; }
    }
}
