//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_Marcin
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenia
    {
        public int ID_wypozyczenia { get; set; }
        public System.DateTime Data_wypozyczenia { get; set; }
        public System.DateTime Data_zwrotu { get; set; }
        public int ID_pracownika { get; set; }
        public int ID_klienta { get; set; }
        public int ID_samochodu { get; set; }
        public int Stan_licznika_przed { get; set; }
        public int Stan_licznika_po { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual pracownicy pracownicy { get; set; }
        public virtual samochody samochody { get; set; }
    }
}
